spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace  # parameter binding 까지 보여줌